services:
  step-ca:
    build: .
    restart: unless-stopped
    ports:
      - "${STEP_CA_PORT}:8443"
    environment:
      DOMAIN:
      STEP_CA_NAME:
      STEP_CA_DNS:
      STEP_CA_PASSWORD:
      STEP_PROVISIONER_NAME:
      STEP_PROVISIONER_PASSWORD:
    volumes:
      - ./data:/home/step
      - ./nginx-config:/nginx-config
